"""initial schema

Revision ID: 66b4e65ebc4e
Revises: 
Create Date: 2026-05-21 14:25:21.458221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66b4e65ebc4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'radiologist', 'technologist', 'referring', name='userrole'), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('visible_id_counters',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'year')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('visible_id', sa.String(length=20), nullable=False),
    sa.Column('mrn', sa.String(length=64), nullable=False),
    sa.Column('name_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('phone_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('email_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('address_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('emergency_contact_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'mrn', name='uq_patient_org_mrn'),
    sa.UniqueConstraint('org_id', 'visible_id', name='uq_patient_org_visible_id')
    )
    op.create_index(op.f('ix_patients_org_id'), 'patients', ['org_id'], unique=False)
    op.create_index(op.f('ix_patients_visible_id'), 'patients', ['visible_id'], unique=False)
    op.create_table('patient_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_type', sa.String(length=32), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assign_doctor_active', 'patient_assignments', ['doctor_user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_patient_assignments_doctor_user_id'), 'patient_assignments', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_patient_id'), 'patient_assignments', ['patient_id'], unique=False)
    op.create_table('patient_insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('policy_number_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('group_number', sa.String(length=64), nullable=True),
    sa.Column('subscriber_name_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_insurance_patient_id'), 'patient_insurance', ['patient_id'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('modality', sa.Enum('CXR', 'CT_BRAIN', 'CT_CHEST', 'MAMMO', 'DENTAL', 'MSK', 'MRI_SPINE', 'MRI_KNEE', 'MRI_PROSTATE', 'MRI_BREAST', 'MRI_CARDIAC', 'MRI_SHOULDER', 'US', 'PET', name='modality'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'awaiting_review', 'completed', 'critical', 'failed', name='studystatus'), nullable=False),
    sa.Column('urgency', sa.Enum('routine', 'urgent', 'stat', name='urgency'), nullable=False),
    sa.Column('ordered_by', sa.UUID(), nullable=False),
    sa.Column('assigned_radiologist', sa.UUID(), nullable=True),
    sa.Column('source_image_key', sa.Text(), nullable=False),
    sa.Column('source_image_sha256', sa.String(length=64), nullable=False),
    sa.Column('study_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_radiologist'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_assigned_radiologist'), 'studies', ['assigned_radiologist'], unique=False)
    op.create_index('ix_studies_dashboard', 'studies', ['assigned_radiologist', 'status', 'study_datetime'], unique=False)
    op.create_index(op.f('ix_studies_org_id'), 'studies', ['org_id'], unique=False)
    op.create_index('ix_studies_org_status', 'studies', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_studies_patient_id'), 'studies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_studies_status'), 'studies', ['status'], unique=False)
    op.create_index(op.f('ix_studies_urgency'), 'studies', ['urgency'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_patient_id'), 'clinical_notes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_notes_study_id'), 'clinical_notes', ['study_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('prediction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_finding', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('pdf_key', sa.Text(), nullable=False),
    sa.Column('heatmap_key', sa.Text(), nullable=True),
    sa.Column('ai_service_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinician_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_study_id'), 'reports', ['study_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_study_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_clinical_notes_study_id'), table_name='clinical_notes')
    op.drop_index(op.f('ix_clinical_notes_patient_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_studies_urgency'), table_name='studies')
    op.drop_index(op.f('ix_studies_status'), table_name='studies')
    op.drop_index(op.f('ix_studies_patient_id'), table_name='studies')
    op.drop_index('ix_studies_org_status', table_name='studies')
    op.drop_index(op.f('ix_studies_org_id'), table_name='studies')
    op.drop_index('ix_studies_dashboard', table_name='studies')
    op.drop_index(op.f('ix_studies_assigned_radiologist'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_patient_insurance_patient_id'), table_name='patient_insurance')
    op.drop_table('patient_insurance')
    op.drop_index(op.f('ix_patient_assignments_patient_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_doctor_user_id'), table_name='patient_assignments')
    op.drop_index('ix_assign_doctor_active', table_name='patient_assignments')
    op.drop_table('patient_assignments')
    op.drop_index(op.f('ix_patients_visible_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_org_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('visible_id_counters')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('orgs')
    # ### end Alembic commands ###
